package com.fshows.commons.model;

import java.io.Serializable;

public class LpLiquidatorStoreAuth implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.store_id
     *
     * @mbggenerated
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.liquidator_id
     *
     * @mbggenerated
     */
    private String liquidatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.id_card_num
     *
     * @mbggenerated
     */
    private String idCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.id_card_name
     *
     * @mbggenerated
     */
    private String idCardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.store_address
     *
     * @mbggenerated
     */
    private String storeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.id_card_hand_img
     *
     * @mbggenerated
     */
    private String idCardHandImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.store_front_img
     *
     * @mbggenerated
     */
    private String storeFrontImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.business_license_img
     *
     * @mbggenerated
     */
    private String businessLicenseImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.update_time
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.district_code
     *
     * @mbggenerated
     */
    private String districtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.business_license
     *
     * @mbggenerated
     */
    private String businessLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.business_license_type
     *
     * @mbggenerated
     */
    private String businessLicenseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_liquidator_store_auth.contact_type
     *
     * @mbggenerated
     */
    private String contactType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lp_liquidator_store_auth
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.id
     *
     * @return the value of lp_liquidator_store_auth.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.id
     *
     * @param id the value for lp_liquidator_store_auth.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.store_id
     *
     * @return the value of lp_liquidator_store_auth.store_id
     *
     * @mbggenerated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.store_id
     *
     * @param storeId the value for lp_liquidator_store_auth.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.liquidator_id
     *
     * @return the value of lp_liquidator_store_auth.liquidator_id
     *
     * @mbggenerated
     */
    public String getLiquidatorId() {
        return liquidatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.liquidator_id
     *
     * @param liquidatorId the value for lp_liquidator_store_auth.liquidator_id
     *
     * @mbggenerated
     */
    public void setLiquidatorId(String liquidatorId) {
        this.liquidatorId = liquidatorId == null ? null : liquidatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.id_card_num
     *
     * @return the value of lp_liquidator_store_auth.id_card_num
     *
     * @mbggenerated
     */
    public String getIdCardNum() {
        return idCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.id_card_num
     *
     * @param idCardNum the value for lp_liquidator_store_auth.id_card_num
     *
     * @mbggenerated
     */
    public void setIdCardNum(String idCardNum) {
        this.idCardNum = idCardNum == null ? null : idCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.id_card_name
     *
     * @return the value of lp_liquidator_store_auth.id_card_name
     *
     * @mbggenerated
     */
    public String getIdCardName() {
        return idCardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.id_card_name
     *
     * @param idCardName the value for lp_liquidator_store_auth.id_card_name
     *
     * @mbggenerated
     */
    public void setIdCardName(String idCardName) {
        this.idCardName = idCardName == null ? null : idCardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.store_address
     *
     * @return the value of lp_liquidator_store_auth.store_address
     *
     * @mbggenerated
     */
    public String getStoreAddress() {
        return storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.store_address
     *
     * @param storeAddress the value for lp_liquidator_store_auth.store_address
     *
     * @mbggenerated
     */
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress == null ? null : storeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.id_card_hand_img
     *
     * @return the value of lp_liquidator_store_auth.id_card_hand_img
     *
     * @mbggenerated
     */
    public String getIdCardHandImg() {
        return idCardHandImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.id_card_hand_img
     *
     * @param idCardHandImg the value for lp_liquidator_store_auth.id_card_hand_img
     *
     * @mbggenerated
     */
    public void setIdCardHandImg(String idCardHandImg) {
        this.idCardHandImg = idCardHandImg == null ? null : idCardHandImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.store_front_img
     *
     * @return the value of lp_liquidator_store_auth.store_front_img
     *
     * @mbggenerated
     */
    public String getStoreFrontImg() {
        return storeFrontImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.store_front_img
     *
     * @param storeFrontImg the value for lp_liquidator_store_auth.store_front_img
     *
     * @mbggenerated
     */
    public void setStoreFrontImg(String storeFrontImg) {
        this.storeFrontImg = storeFrontImg == null ? null : storeFrontImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.business_license_img
     *
     * @return the value of lp_liquidator_store_auth.business_license_img
     *
     * @mbggenerated
     */
    public String getBusinessLicenseImg() {
        return businessLicenseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.business_license_img
     *
     * @param businessLicenseImg the value for lp_liquidator_store_auth.business_license_img
     *
     * @mbggenerated
     */
    public void setBusinessLicenseImg(String businessLicenseImg) {
        this.businessLicenseImg = businessLicenseImg == null ? null : businessLicenseImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.create_time
     *
     * @return the value of lp_liquidator_store_auth.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.create_time
     *
     * @param createTime the value for lp_liquidator_store_auth.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.update_time
     *
     * @return the value of lp_liquidator_store_auth.update_time
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.update_time
     *
     * @param updateTime the value for lp_liquidator_store_auth.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.status
     *
     * @return the value of lp_liquidator_store_auth.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.status
     *
     * @param status the value for lp_liquidator_store_auth.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.province_code
     *
     * @return the value of lp_liquidator_store_auth.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.province_code
     *
     * @param provinceCode the value for lp_liquidator_store_auth.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.city_code
     *
     * @return the value of lp_liquidator_store_auth.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.city_code
     *
     * @param cityCode the value for lp_liquidator_store_auth.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.district_code
     *
     * @return the value of lp_liquidator_store_auth.district_code
     *
     * @mbggenerated
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.district_code
     *
     * @param districtCode the value for lp_liquidator_store_auth.district_code
     *
     * @mbggenerated
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.business_license
     *
     * @return the value of lp_liquidator_store_auth.business_license
     *
     * @mbggenerated
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.business_license
     *
     * @param businessLicense the value for lp_liquidator_store_auth.business_license
     *
     * @mbggenerated
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense == null ? null : businessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.business_license_type
     *
     * @return the value of lp_liquidator_store_auth.business_license_type
     *
     * @mbggenerated
     */
    public String getBusinessLicenseType() {
        return businessLicenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.business_license_type
     *
     * @param businessLicenseType the value for lp_liquidator_store_auth.business_license_type
     *
     * @mbggenerated
     */
    public void setBusinessLicenseType(String businessLicenseType) {
        this.businessLicenseType = businessLicenseType == null ? null : businessLicenseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.card_no
     *
     * @return the value of lp_liquidator_store_auth.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.card_no
     *
     * @param cardNo the value for lp_liquidator_store_auth.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_liquidator_store_auth.contact_type
     *
     * @return the value of lp_liquidator_store_auth.contact_type
     *
     * @mbggenerated
     */
    public String getContactType() {
        return contactType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_liquidator_store_auth.contact_type
     *
     * @param contactType the value for lp_liquidator_store_auth.contact_type
     *
     * @mbggenerated
     */
    public void setContactType(String contactType) {
        this.contactType = contactType == null ? null : contactType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_liquidator_store_auth
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", storeId=").append(storeId);
        sb.append(", liquidatorId=").append(liquidatorId);
        sb.append(", idCardNum=").append(idCardNum);
        sb.append(", idCardName=").append(idCardName);
        sb.append(", storeAddress=").append(storeAddress);
        sb.append(", idCardHandImg=").append(idCardHandImg);
        sb.append(", storeFrontImg=").append(storeFrontImg);
        sb.append(", businessLicenseImg=").append(businessLicenseImg);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", status=").append(status);
        sb.append(", provinceCode=").append(provinceCode);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", districtCode=").append(districtCode);
        sb.append(", businessLicense=").append(businessLicense);
        sb.append(", businessLicenseType=").append(businessLicenseType);
        sb.append(", cardNo=").append(cardNo);
        sb.append(", contactType=").append(contactType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_liquidator_store_auth
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LpLiquidatorStoreAuth other = (LpLiquidatorStoreAuth) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getLiquidatorId() == null ? other.getLiquidatorId() == null : this.getLiquidatorId().equals(other.getLiquidatorId()))
            && (this.getIdCardNum() == null ? other.getIdCardNum() == null : this.getIdCardNum().equals(other.getIdCardNum()))
            && (this.getIdCardName() == null ? other.getIdCardName() == null : this.getIdCardName().equals(other.getIdCardName()))
            && (this.getStoreAddress() == null ? other.getStoreAddress() == null : this.getStoreAddress().equals(other.getStoreAddress()))
            && (this.getIdCardHandImg() == null ? other.getIdCardHandImg() == null : this.getIdCardHandImg().equals(other.getIdCardHandImg()))
            && (this.getStoreFrontImg() == null ? other.getStoreFrontImg() == null : this.getStoreFrontImg().equals(other.getStoreFrontImg()))
            && (this.getBusinessLicenseImg() == null ? other.getBusinessLicenseImg() == null : this.getBusinessLicenseImg().equals(other.getBusinessLicenseImg()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getProvinceCode() == null ? other.getProvinceCode() == null : this.getProvinceCode().equals(other.getProvinceCode()))
            && (this.getCityCode() == null ? other.getCityCode() == null : this.getCityCode().equals(other.getCityCode()))
            && (this.getDistrictCode() == null ? other.getDistrictCode() == null : this.getDistrictCode().equals(other.getDistrictCode()))
            && (this.getBusinessLicense() == null ? other.getBusinessLicense() == null : this.getBusinessLicense().equals(other.getBusinessLicense()))
            && (this.getBusinessLicenseType() == null ? other.getBusinessLicenseType() == null : this.getBusinessLicenseType().equals(other.getBusinessLicenseType()))
            && (this.getCardNo() == null ? other.getCardNo() == null : this.getCardNo().equals(other.getCardNo()))
            && (this.getContactType() == null ? other.getContactType() == null : this.getContactType().equals(other.getContactType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_liquidator_store_auth
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getLiquidatorId() == null) ? 0 : getLiquidatorId().hashCode());
        result = prime * result + ((getIdCardNum() == null) ? 0 : getIdCardNum().hashCode());
        result = prime * result + ((getIdCardName() == null) ? 0 : getIdCardName().hashCode());
        result = prime * result + ((getStoreAddress() == null) ? 0 : getStoreAddress().hashCode());
        result = prime * result + ((getIdCardHandImg() == null) ? 0 : getIdCardHandImg().hashCode());
        result = prime * result + ((getStoreFrontImg() == null) ? 0 : getStoreFrontImg().hashCode());
        result = prime * result + ((getBusinessLicenseImg() == null) ? 0 : getBusinessLicenseImg().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getProvinceCode() == null) ? 0 : getProvinceCode().hashCode());
        result = prime * result + ((getCityCode() == null) ? 0 : getCityCode().hashCode());
        result = prime * result + ((getDistrictCode() == null) ? 0 : getDistrictCode().hashCode());
        result = prime * result + ((getBusinessLicense() == null) ? 0 : getBusinessLicense().hashCode());
        result = prime * result + ((getBusinessLicenseType() == null) ? 0 : getBusinessLicenseType().hashCode());
        result = prime * result + ((getCardNo() == null) ? 0 : getCardNo().hashCode());
        result = prime * result + ((getContactType() == null) ? 0 : getContactType().hashCode());
        return result;
    }
}